### PR TITLE
User Ports Removed from Command and Query Interfaces

### LINKED ISSUE #31: Remove User Ports from Command and Query Interfaces
We need to remove the UserCommandPort and UserQueryPort entries from the command and query port interfaces within the presentation layer. 

## Files to Update:
`internal/application/presentation/port/command/command.go`

- After Change:
```go
package application

// CommandPort is a port for Hexagonal Architecture Pattern.
// It is used to communicate with the application layer.
type CommandPort interface {
    LoggingCommandPort
    AuthenticationCommandPort
}
```
## Files to Update:
`internal/application/presentation/port/query/query.go``

- After Change:
```go
package application

// QueryPort is a port for Hexagonal Architecture Pattern.
// It is used to communicate with the application layer.
type QueryPort interface {
}
```

The changes will be merged into the first/hsm/1/create-first branch first. Therefore, set the base branch of the pull request as first/hsm/1/create-first.

### PR DESCRIPTION
**Pull request by Smnrgcl**
Close #31 

internal/application/presentation/port/command/command.go
internal/application/presentation/port/query/query.go 

Removed user ports from **command.go** and **query.go** files in directories.

### CODE REVIEW

**Review by Feyzanrs — APPROVED** [review]
:)

**Comment by Sddilora** [comment]
> :)

"What was the smile for?" :)

**Comment by Feyzanrs** [comment]
Smiling is beautiful :)

**Comment by Sddilora** [comment]
> Smiling is beautiful :)

:)

**Review by Sddilora — APPROVED** [review]
:)

**Pull request merged**
